#!/usr/bin/env python3
"""Eurorack module pages and the power budget, generated from eurorack/evidence + eurorack/overrides.yaml.

Called by tools/build_site.py. Field statuses:
  confirmed = two or more sources agree      single = one source only        conflict = sources disagree
  inferred/override = a human decision with its reasoning shown      missing = no source stated it
"""
import hashlib
import json
from collections import Counter
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
GEN = "<!-- GENERATED by tools/build_eurorack.py from eurorack/evidence and overrides.yaml. Do not edit. -->"
GEN_BUDGET = "<!-- GENERATED by tools/build_eurorack.py from graph/public/budget.json (built by tools/build_graph.py). Do not edit. -->"
FIELDS = [("hp", "Width (HP)"), ("depth_mm", "Depth (mm)"), ("ma_p12", "+12V (mA)"), ("ma_m12", "-12V (mA)"), ("ma_p5", "+5V (mA)")]
RAILS = FIELDS[2:]
RANK = {"conflict": 5, "missing": 4, "inferred": 3, "override": 2, "single": 1, "confirmed": 0}


def inputs_digest():
    """Hash of the DATA the power budget depends on (not file bytes, so comment edits do not count).
    build_graph.py stores it in graph/public/budget.json; this module refuses a snapshot that no longer matches."""
    inv = yaml.safe_load((ROOT / "inventory.yaml").read_text())["items"]
    conn = yaml.safe_load((ROOT / "connections.yaml").read_text())
    payload = {
        "items": sorted([i["id"], i["category"], i.get("in_use", True), i.get("format")] for i in inv if i["category"].startswith("eurorack")),
        "cases": conn.get("cases"), "placements": conn.get("placements"),
        "overrides": yaml.safe_load((ROOT / "eurorack" / "overrides.yaml").read_text()),
        "attestations": yaml.safe_load((ROOT / "eurorack" / "attestations.yaml").read_text()),
        "evidence": {p.stem: json.loads(p.read_text()) for p in sorted((ROOT / "eurorack" / "evidence").glob("*.json"))},
    }
    return hashlib.sha256(json.dumps(payload, sort_keys=True, default=str).encode()).hexdigest()


def load_budget():
    """The per-supply power budget computed by the knowledge graph. Fails loudly if it is missing or stale."""
    path = ROOT / "graph" / "public" / "budget.json"
    if not path.exists():
        raise SystemExit("graph/public/budget.json is missing. Run: .venv-graph/bin/python tools/build_graph.py")
    snap = json.loads(path.read_text())
    if snap["inputs_sha256"] != inputs_digest():
        raise SystemExit("graph/public/budget.json is STALE (placements, specs, overrides or in-use flags changed since it was built). "
                         "Run: .venv-graph/bin/python tools/build_graph.py")
    return snap


def resolve(field, sources, override):
    if field in override:
        o = override[field]
        return {"value": o["value"], "status": o.get("status", "override"), "basis": o.get("basis", ""), "seen": []}
    seen = [(s["tier"], s["url"], s["values"][field], s["values"].get(field + "_line", "")) for s in sources if field in s["values"]]
    if not seen:
        return {"value": None, "status": "missing", "basis": "", "seen": []}
    counts = Counter(v[2] for v in seen)
    if len(counts) == 1:
        return {"value": seen[0][2], "status": "confirmed" if len(seen) >= 2 else "single", "basis": "", "seen": seen}
    top, n = counts.most_common(1)[0]
    value = top if n > len(seen) / 2 else max(counts)            # conservative for power: the larger figure
    return {"value": value, "status": "conflict", "basis": "Sources disagree: " + ", ".join(f"{t}={v}" for t, _, v, _ in seen), "seen": seen}


def build(items, docs):
    overrides = yaml.safe_load((ROOT / "eurorack" / "overrides.yaml").read_text()) or {}
    cfg = yaml.safe_load((ROOT / "eurorack" / "sources.yaml").read_text())["modules"]
    mods = {}
    for it in items:
        ev = ROOT / "eurorack" / "evidence" / f"{it['id']}.json"
        if not it["category"].startswith("eurorack") or not ev.exists():
            continue
        rec, ov = json.loads(ev.read_text()), overrides.get(it["id"], {})
        res = {f: resolve(f, rec["sources"], ov) for f, _ in FIELDS}
        mods[it["id"]] = {"item": it, "rec": rec, "ov": ov, "res": res,
                          # "weakest" ignores fields the budget does not need when absent: many modules simply do not state a
                          # +5V figure or a depth. Their absence is shown on the module page, not here.
                          "worst": max((r["status"] for f, r in res.items() if not (r["status"] == "missing" and f in ("ma_p5", "depth_mm"))),
                                       key=lambda s: RANK[s]),
                          "confirmed": sum(1 for r in res.values() if r["status"] == "confirmed")}

    out = docs / "eurorack"
    out.mkdir(parents=True, exist_ok=True)
    for old in out.glob("*.md"):
        old.unlink()

    def fmt(r):
        return "-" if r["value"] is None else str(r["value"])

    # ---- module cards ----
    for mid, m in mods.items():
        it, res, ov, rec = m["item"], m["res"], m["ov"], m["rec"]
        supply = ov.get("role") == "supply"
        fm = {"title": it["name"], "doc_type": "eurorack-module", "module": mid, "manufacturer": it.get("manufacturer"),
              "category": it["category"], "format": it.get("format", "3U"), "in_use": it.get("in_use", True),
              "function": ov.get("function"), "role": ov.get("role", "module"),
              "specs": {"hp": res["hp"]["value"], "depth_mm": res["depth_mm"]["value"],
                        ("capacity_ma" if supply else "power_ma"): {"+12V": res["ma_p12"]["value"], "-12V": res["ma_m12"]["value"], "+5V": res["ma_p5"]["value"]}},
              "spec_status": {f: r["status"] for f, r in res.items()}, "identified_as": rec.get("match_note"),
              "content_status": "generated"}
        fm = {k: v for k, v in fm.items() if v is not None}
        b = [f"# {it['name']}", ""]
        if ov.get("function"):
            b += [f"**Function:** {ov['function']}. *(Description from ModularGrid/retailer text; not verified against a manual.)*", ""]
        if rec.get("match_note"):
            b += [f"> **Identification:** {rec['match_note']}", ""]
        if it.get("note"):
            b += [f"> {it['note']}", ""]
        if ov.get("notes"):
            b += [f"> {ov['notes']}", ""]
        b += ["## Specifications", "", "| Field | Value | Status | Basis |", "|---|---|---|---|"]
        for f, label in FIELDS:
            r = res[f]
            name = label.replace("(mA)", "(mA supplied)") if supply and f.startswith("ma_") else label
            if it["category"] == "eurorack-case" and f == "hp":
                name = "Usable case area (HP)"
            src = "; ".join(f"{t}: {v}" for t, _, v, _ in r["seen"]) or "no source stated it"
            b.append(f"| {name} | {fmt(r)} | {r['status']} | {r['basis'] or src} |")
        b += ["", "*confirmed = two or more sources agree; single = one source only; inferred/override = a decision with the reasoning shown; missing = not stated in any source that could be read.*", "",
              "## Evidence: the exact lines each number came from", "", "| Field | Source | Value | Line | Page |", "|---|---|---|---|---|"]
        for f, label in FIELDS:
            for tier, url, val, line in res[f]["seen"]:
                b.append(f"| {label} | {tier} | {val} | `{line.replace('|', '/')}` | <{url}> |")
        b += ["", f"Fetched {rec['fetched']}. Pages: " + ", ".join(f"<{s['url']}> (HTTP {s['http']})" for s in rec["sources"])]
        (out / f"{mid}.md").write_text(f"---\n{yaml.safe_dump(fm, sort_keys=False, allow_unicode=True, width=1000)}---\n\n{GEN}\n\n" + "\n".join(b) + "\n", encoding="utf-8")

    # ---- overview ----
    supply_ids = [k for k, m in mods.items() if m["ov"].get("role") == "supply"]
    consumers = [m for k, m in mods.items() if k not in supply_ids and m["item"].get("in_use", True) is not False]
    rows = ["| Module | Format | HP | +12V | -12V | +5V | Weakest field status |", "|---|---|---|---|---|---|---|"]
    for k, m in sorted(mods.items(), key=lambda kv: kv[1]["item"]["name"].lower()):
        r = m["res"]
        rows.append(f"| [{m['item']['name']}]({k}.md) | {m['item'].get('format', '3U')} | {fmt(r['hp'])} | {fmt(r['ma_p12'])} | {fmt(r['ma_m12'])} | {fmt(r['ma_p5'])} | {m['worst']} |")
    pending = [i for i in items if i["category"].startswith("eurorack") and i["id"] not in mods and i.get("in_use", True) is not False
               and not i.get("no_spec_page")]
    unused = [i for i in items if i["category"].startswith("eurorack") and i.get("in_use", True) is False]
    tally = Counter(r["status"] for m in mods.values() for r in m["res"].values())
    b = ["# Eurorack", "", f"{len(mods)} modules have spec pages. Every number keeps the source it came from; see each module's *Evidence* table.", "",
         "Field status across all modules: " + ", ".join(f"{n} {s}" for s, n in sorted(tally.items(), key=lambda x: -x[1])) + ".", "",
         "See the [power budget](power-budget.md).", ""] + rows
    if pending:
        b += ["", "## Not yet covered", "", "In use, but not identified confidently enough to look up (see the inventory's open questions):", ""] + [f"- {i['name']}" for i in pending]
    if unused:
        b += ["", "## Marked unused", ""] + [f"- {i['name']}" for i in unused]
    (out / "index.md").write_text(f"---\ntitle: Eurorack\ndoc_type: eurorack-index\ncontent_status: generated\n---\n\n{GEN}\n\n" + "\n".join(b) + "\n", encoding="utf-8")

    # ---- power budget: computed by the knowledge graph (tools/build_graph.py -> graph/public/budget.json) ----
    gb = load_budget()
    conn = yaml.safe_load((ROOT / "connections.yaml").read_text())
    setup_id, setup = next(iter(gb["setups"].items()))
    sup_list = setup["supplies"]
    name_of = {i["id"]: i["name"] for i in items}
    cases = {k["id"]: k for k in conn.get("cases", []) if k["setup"] == setup_id}
    powered = {p["module"]: p["powered_by"] for p in conn.get("placements", []) if p["setup"] == setup_id}
    b = ["# Power budget", "",
         "Each supply is compared only with the modules it actually feeds. Which module sits in which case, and which supply feeds it, "
         "is recorded in `connections.yaml` (confirmed by the owner, 2026-09-20), and the sums below are computed over the knowledge graph "
         "by `tools/build_graph.py`, not by hand. This is a paper budget from published figures, not a measurement.", "",
         "| Supply | Rail | Draw (mA) | Capacity (mA) | Load | Modules | With no figure |", "|---|---|---|---|---|---|---|"]
    for s_ in sup_list:
        for rail in ("+12V", "-12V", "+5V"):
            r = s_["rails"][rail]
            lower = " (lower bound)" if r["modules_without_figure"] else ""
            b.append(f"| {s_['name']} ({s_['kind']}) | {rail} | {r['draw_ma']}{lower} | {r['capacity_ma'] or '-'} | "
                     f"{'-' if r['pct'] is None else str(r['pct']) + '%'} | {r['modules_counted']} | {len(r['modules_without_figure'])} |")
    b += ["", "Load is draw as a share of capacity. A rail marked *lower bound* omits modules whose figure no source stated. "
          "The NiftyCASE figures are labelled *peak* by the maker; its continuous capacity may be lower.", "",
          "## What each supply feeds", ""]
    b += [f"- **{s_['name']}**: " + ", ".join(f"[{name_of[m]}]({m}.md)" for m in s_["modules"]) for s_ in sup_list]
    used = Counter()
    for p in conn.get("placements", []):
        if p["setup"] == setup_id and p["module"] in mods:
            used[(p["case"], p.get("row") or mods[p["module"]]["item"].get("format", "3U"))] += mods[p["module"]]["res"]["hp"]["value"] or 0
    fit = []
    for cid, k in cases.items():
        for f_ in dict.fromkeys(r_["format"] for r_ in k["rows"]):
            fit.append(f"{name_of[cid]} {f_}: {used[(cid, f_)]} of {sum(r_['hp'] for r_ in k['rows'] if r_['format'] == f_)} HP")
    b += ["", "**Space:** " + "; ".join(fit) + ". The custom case's 3U figure includes the 4 HP CP1A. "
          "1U-format (Intellijel) modules use their own row, and their HP is as listed by ModularGrid.", "",
          "## Per module", "", "| Module | Powered by | HP | +12V | -12V | +5V | Weakest status |", "|---|---|---|---|---|---|---|"]
    for m in sorted(consumers, key=lambda m: -(m["res"]["ma_p12"]["value"] or 0)):
        r = m["res"]
        b.append(f"| [{m['item']['name']}]({m['item']['id']}.md) | {name_of.get(powered.get(m['item']['id']), '-')} | {fmt(r['hp'])} | "
                 f"{fmt(r['ma_p12'])} | {fmt(r['ma_m12'])} | {fmt(r['ma_p5'])} | {m['worst']} |")
    if pending:
        b += ["", "## Not in this budget", ""] + [f"- {i['name']}: not identified yet" for i in pending]
    att = sum(r_["owner_attested"] for s_ in sup_list for r_ in s_["rails"].values())
    fig = sum(sum(r_["figure_status"].values()) for s_ in sup_list for r_ in s_["rails"].values())
    inferred = sum(r_["figure_status"].get("inferred", 0) for s_ in sup_list for r_ in s_["rails"].values())
    b += ["", "## How much to trust it", "",
          f"{fig} module draw figures feed these sums. **{att} are attested correct by the owner**, who sourced the draw values from the "
          "manufacturers (see `eurorack/attestations.yaml`); the attestation is recorded separately and does not change each field's evidence status. "
          f"{inferred} are zero-draw assumptions for passive modules; those were inferred, not sourced, and are labelled *inferred* "
          "on the module pages. Supply capacity figures are not covered by the attestation."]
    (out / "power-budget.md").write_text(f"---\ntitle: Power budget\ndoc_type: eurorack-budget\ncontent_status: generated\n---\n\n{GEN_BUDGET}\n\n" + "\n".join(b) + "\n", encoding="utf-8")

    nav = [{"Overview": "eurorack/index.md"}, {"Power budget": "eurorack/power-budget.md"}] + \
          [{m["item"]["name"]: f"eurorack/{k}.md"} for k, m in sorted(mods.items(), key=lambda kv: kv[1]["item"]["name"].lower())]
    llms = ["## Eurorack", "", "- [Eurorack overview](eurorack/): module specs with sources", "- [Power budget](eurorack/power-budget/): rail totals vs supply capacity"] + \
           [f"- [{m['item']['name']}](eurorack/{k}/)" + (f": {m['ov']['function']}" if m["ov"].get("function") else "") for k, m in sorted(mods.items(), key=lambda kv: kv[1]["item"]["name"].lower())] + [""]
    cards = {k: f"specs {m['confirmed']}/5 confirmed, weakest: {m['worst']}" for k, m in mods.items()}
    matrix = [{"id": k, "name": m["item"]["name"], "format": m["item"].get("format", "3U"),
               "statuses": {f: m["res"][f]["status"] for f, _ in FIELDS}, "values": {f: m["res"][f]["value"] for f, _ in FIELDS}}
              for k, m in sorted(mods.items(), key=lambda kv: kv[1]["item"]["name"].lower())]
    return {"matrix": matrix, "fields": FIELDS, "nav": nav, "llms": llms, "cards": cards, "count": len(mods), "consumers": len(consumers),
            "tally": dict(tally), "budget": sup_list, "supplies": [s_["name"] for s_ in sup_list]}
