#!/usr/bin/env python3
"""Generate everything in docs/ that is not a converted manual section, plus mkdocs.yml.

    .venv/bin/python tools/build_site.py

Inputs : inventory.yaml, tools/manifest.yaml, docs/manuals/*/NN-*.md (frontmatter), VOCAB.yaml
Outputs: docs/index.md, docs/inventory.md, docs/devices/*.md, docs/topics/*.md, docs/llms.txt, mkdocs.yml
Nothing here is hand-edited; change the inputs and re-run.
"""
import json
import re
from collections import defaultdict
from pathlib import Path

import yaml

from build_eurorack import build as build_eurorack
from site_theme import EXTRA_CSS, THEME

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
GEN_NOTE = "<!-- GENERATED by tools/build_site.py. Edit inventory.yaml / manifest.yaml, not this file. -->"


def read_fm(path):
    text = path.read_text(encoding="utf-8")
    m = re.match(r"---\n(.*?)\n---\n", text, re.S)
    return (yaml.safe_load(m.group(1)) if m else {}), text


def write(path, fm, body):
    path.parent.mkdir(parents=True, exist_ok=True)
    head = f"---\n{yaml.safe_dump(fm, sort_keys=False, allow_unicode=True, width=1000)}---\n\n" if fm else ""
    path.write_text(f"{head}{GEN_NOTE}\n\n{body.strip()}\n", encoding="utf-8")


def collect_sections():
    """{manual_id: [(filename, frontmatter)]} in file order."""
    out = {}
    for mdir in sorted((DOCS / "manuals").glob("*/")):
        secs = []
        for f in sorted(mdir.glob("[0-9]*.md")):
            fm, _ = read_fm(f)
            secs.append((f.name, fm))
        if secs:
            out[mdir.name] = secs
    return out


def main():
    inv = yaml.safe_load((ROOT / "inventory.yaml").read_text())
    man = yaml.safe_load((ROOT / "tools" / "manifest.yaml").read_text())["manuals"]
    vocab = yaml.safe_load((ROOT / "VOCAB.yaml").read_text())["tags"]
    sections = collect_sections()
    manuals_by_device = defaultdict(list)
    for m in man:
        if m["id"] in sections:
            manuals_by_device[m["device"]].append(m)

    items = inv["items"]
    eu = build_eurorack(items, DOCS)

    # ---- device pages (slice devices only) ----
    for it in items:
        if not it.get("slice"):
            continue
        mans = manuals_by_device.get(it["id"], [])
        fm = {"title": it["name"], "doc_type": "device", "device": it["id"],
              "manufacturer": it.get("manufacturer"), "model": it.get("model"), "category": it["category"],
              "status": it["status"], "revision": it.get("revision"),
              "manual_status": "ingested" if mans else "blocked",
              "manuals": [m["id"] for m in mans], "content_status": "generated"}
        fm = {k: v for k, v in fm.items() if v is not None}
        b = [f"# {it['name']}", ""]
        if it.get("role"):
            b += [f"**Role:** {it['role']}", ""]
        if it.get("note"):
            b += [f"> {it['note']}", ""]
        b += ["## Manuals", ""]
        if mans:
            for m in mans:
                n = len(sections[m["id"]])
                b.append(f"- [{m['title']}](../manuals/{m['id']}/index.md): {m['doc_type']}, {m['doc_version']}, {n} sections. {m['applies_to']}")
        else:
            b.append(f"**No manual ingested yet.** {it.get('manual_blocked', '')}")
        if mans:
            b += ["", "## Find by topic", ""]
            by_tag = defaultdict(list)
            for m in mans:
                for fname, sfm in sections[m["id"]]:
                    for t in sfm.get("tags", []):
                        by_tag[t].append((m["id"], fname, sfm["title"]))
            for tag in vocab:
                if tag in by_tag:
                    links = ", ".join(f"[{t}](../manuals/{mid}/{fn})" for mid, fn, t in by_tag[tag][:12])
                    more = f" (+{len(by_tag[tag]) - 12} more)" if len(by_tag[tag]) > 12 else ""
                    b.append(f"- **{tag}** ({len(by_tag[tag])}): {links}{more}")
        b += ["", "## Connections and routing", "",
              "Not yet documented. How this device is wired into your current studio (audio, MIDI, USB, clock) has not "
              "been confirmed by the owner, and the Feb 2025 routing notes predate the current setup, so none are carried over."]
        write(DOCS / "devices" / f"{it['id']}.md", fm, "\n".join(b))

    # ---- topic pages (cross-device) ----
    topic_counts = {}
    for tag in vocab:
        rows = defaultdict(list)
        for mid, secs in sections.items():
            for fname, sfm in secs:
                if tag in sfm.get("tags", []):
                    rows[(sfm["device"], mid)].append((fname, sfm))
        if not rows:
            continue
        topic_counts[tag] = sum(len(v) for v in rows.values())
        b = [f"# Topic: {tag}", "", f"Sections tagged `{tag}`, grouped by device. Tags are assigned by keyword rules "
             f"(see `VOCAB.yaml`) and can be wrong; check the section itself.", ""]
        for (dev, mid), secs in sorted(rows.items()):
            name = next((i["name"] for i in items if i["id"] == dev), dev)
            b += [f"## {name}", ""]
            b += [f"- [{s['title']}](../manuals/{mid}/{fn})" + (f": {s['description']}" if s.get("description") else "")
                  for fn, s in secs]
            b.append("")
        write(DOCS / "topics" / f"{tag}.md", {"title": f"Topic: {tag}", "doc_type": "topic", "content_status": "generated"}, "\n".join(b))
    write(DOCS / "topics" / "index.md", {"title": "Topics", "doc_type": "topic-index", "content_status": "generated"},
          "# Topics\n\nCross-device views built from section tags.\n\n" +
          "\n".join(f"- [{t}]({t}.md): {n} sections" for t, n in topic_counts.items()))

    # ---- inventory page ----
    cats = defaultdict(list)
    for it in items:
        cats[it["category"]].append(it)
    ingested = {d for d in manuals_by_device}
    b = ["# Inventory", "",
         f"Last updated {inv['updated']}. Status: **owned** = confirmed by the owner, **assumed** = carried over from the Feb 2025 list "
         "and not mentioned when pruning, **unconfirmed** = needs an answer.", ""]
    for cat in sorted(cats):
        b += [f"## {cat}", "", "| Item | Status | Manual | Notes |", "|---|---|---|---|"]
        for it in cats[cat]:
            if it.get("slice"):
                link = f"[{it['name']}](devices/{it['id']}.md)"
                mstat = "ingested" if it["id"] in ingested else "**blocked**"
            elif it["id"] in eu["cards"]:
                link, mstat = f"[{it['name']}](eurorack/{it['id']}.md)", eu["cards"][it["id"]]
            else:
                link, mstat = it["name"] + (f" {it['version']}" if it.get("version") else ""), "not started"
            note = " ".join(x for x in [it.get("role", ""), it.get("note", "")] if x)
            status = it["status"] + (" (unused)" if it.get("in_use") is False else "")
            b.append(f"| {link} | {status} | {mstat} | {note} |")
        b.append("")
    b += ["## Removed", "", *[f"- {r['name']}: {r['reason']}" for r in inv.get("removed", [])], "",
          "## Open questions", ""]
    b += [f"- **{i['name']}**: {i['question']}" for i in items if i.get("question")]
    write(DOCS / "inventory.md", {"title": "Inventory", "doc_type": "inventory", "content_status": "generated"}, "\n".join(b))

    # ---- generated project status (so documentation never quotes stale numbers) ----
    n_man, n_sec = len(sections), sum(len(v) for v in sections.values())
    st = ["# Current status", "", "Generated by `tools/build_site.py` on every build; the hand-written pages in this section point here instead of quoting numbers.", "",
          "| Measure | Value |", "|---|---|",
          f"| Manuals ingested | {n_man} ({sum(1 for m in man if m['id'] in sections and m['doc_type'] == 'user-manual')} full manuals, "
          f"{sum(1 for m in man if m['id'] in sections and m['doc_type'] == 'quick-start')} quick starts) |",
          f"| Manual sections (one markdown file each) | {n_sec} |",
          f"| Inventory items | {len(items)} ({sum(1 for i in items if i['category'].startswith('eurorack'))} Eurorack) |",
          f"| Devices with pages | {sum(1 for i in items if i.get('slice'))} |",
          f"| Eurorack modules with spec pages | {eu['count']} ({eu['consumers']} counted as consumers in the budget) |",
          "| Eurorack field status | " + ", ".join(f"{n} {s}" for s, n in sorted(eu['tally'].items(), key=lambda x: -x[1])) + " |", "",
          "## Power budget snapshot", "", "Computed by the knowledge graph: each supply's draw is the sum of published figures for the modules it feeds "
          "(placement is recorded in `connections.yaml`). See the [power budget](../eurorack/power-budget.md) for the caveats.", "",
          "| Supply | Rail | Draw (mA) | Capacity (mA) | Load | Modules with no figure |", "|---|---|---|---|---|---|"]
    st += [f"| {s['name']} | {rail} | {s['rails'][rail]['draw_ma']} | {s['rails'][rail]['capacity_ma']} | {s['rails'][rail]['pct']}% | "
           f"{len(s['rails'][rail]['modules_without_figure'])} |" for s in eu["budget"] for rail in ("+12V", "-12V", "+5V")]
    (ROOT / "data").mkdir(exist_ok=True)
    (ROOT / "data" / "snapshot.json").write_text(json.dumps({
        "manuals": [{"id": m["id"], "title": m["title"], "doc_type": m["doc_type"], "device": m["device"], "sections": len(sections.get(m["id"], []))}
                    for m in man if m["id"] in sections],
        "inventory_items": len(items)}, indent=1))
    write(DOCS / "about" / "status.md", {"title": "Current status", "doc_type": "project-status", "content_status": "generated"}, "\n".join(st))

    # ---- home page ----
    total_secs = sum(len(v) for v in sections.values())
    write(DOCS / "index.md", {"title": "Gear Knowledge Base", "doc_type": "home", "content_status": "generated"},
          f"# Gear Knowledge Base\n\nPersonal, agent-readable notes on studio gear, built from manufacturer manuals.\n\n"
          f"- [Inventory](inventory.md): every piece of gear, its status, and whether its manual is ingested\n"
          f"- [Topics](topics/index.md): find sections across devices (midi, usb, sync-clock, ...)\n"
          f"- [Eurorack](eurorack/index.md): module specs with their sources, and a [power budget](eurorack/power-budget.md)\n"
          f"- Devices in the first slice: " + ", ".join(f"[{i['name']}](devices/{i['id']}.md)" for i in items if i.get('slice')) + "\n\n"
          f"**{len(sections)} manuals, {total_secs} sections ingested.** Each section is one markdown file with "
          f"provenance metadata (source URL, retrieval date, PDF hash). Machine-readable index: [llms.txt](llms.txt).\n\n"
          f"> Manual content is copyright its manufacturers, converted for personal reference. Not for redistribution.")

    # ---- llms.txt (llmstxt.org shape) ----
    L = ["# Gear Knowledge Base", "",
         "> Studio gear inventory and manufacturer-manual sections, one page per section, with provenance metadata.", "",
         "## Inventory", "", "- [Inventory](inventory/): all gear, status, and manual coverage", ""]
    L += ["## Devices", ""] + [f"- [{i['name']}](devices/{i['id']}/)" for i in items if i.get("slice")] + [""]
    for mid, secs in sections.items():
        mt = next(m for m in man if m["id"] == mid)
        L += [f"## {mt['title']}", ""]
        L += [f"- [{sfm['title']}](manuals/{mid}/{fn[:-3]}/)" + (f": {sfm['description']}" if sfm.get("description") else "")
              for fn, sfm in secs] + [""]
    L += eu["llms"]
    (DOCS / "llms.txt").write_text("\n".join(L), encoding="utf-8")

    # ---- mkdocs.yml ----
    nav = [{"Home": "index.md"}, {"Inventory": "inventory.md"},
           {"Devices": [{i["name"]: f"devices/{i['id']}.md"} for i in items if i.get("slice")]}]
    for m in man:
        if m["id"] in sections:
            nav.append({m["title"]: [{"Overview": f"manuals/{m['id']}/index.md"}] +
                        [{sfm["title"]: f"manuals/{m['id']}/{fn}"} for fn, sfm in sections[m["id"]]]})
    about = [("index.md", "Overview"), ("architecture.md", "Architecture"), ("verification.md", "How correctness is checked"),
             ("evaluation.md", "Retrieval evaluation"), ("decisions.md", "Decision log"), ("runbook.md", "Runbook"),
             ("limitations.md", "Limitations and open questions"), ("status.md", "Current status")]
    nav.append({"About this project": [{t: f"about/{f}"} for f, t in about]})
    nav.append({"Eurorack": eu["nav"]})
    nav.append({"Topics": ["topics/index.md"] + [f"topics/{t}.md" for t in topic_counts]})
    cfg = {"site_name": "Gear Knowledge Base", "site_description": "Machine-readable studio gear notes",
           "docs_dir": "docs", "theme": THEME, "extra_css": EXTRA_CSS, "plugins": ["search"], "nav": nav}
    (ROOT / "mkdocs.yml").write_text("# GENERATED by tools/build_site.py (nav is rebuilt from docs/). Do not edit.\n"
                                     + yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True, width=1000), encoding="utf-8")
    try:                                   # optional, git-ignored local additions; absent in a fresh clone
        import local_extras
        local_extras.write(ROOT, cfg)
    except ImportError:
        pass
    print(f"built: {len(sections)} manuals, {total_secs} sections, {sum(1 for i in items if i.get('slice'))} device pages, "
          f"{len(topic_counts)} topic pages, {len(items)} inventory items")


if __name__ == "__main__":
    main()
