#!/usr/bin/env python3
"""Eurorack module pages and the power budget, generated from eurorack/evidence + eurorack/overrides.yaml.

Called by tools/build_site.py. Field statuses:
  confirmed = two or more sources agree      single = one source only        conflict = sources disagree
  inferred/override = a human decision with its reasoning shown      missing = no source stated it
"""
import json
from collections import Counter
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
GEN = "<!-- GENERATED by tools/build_eurorack.py from eurorack/evidence and overrides.yaml. Do not edit. -->"
FIELDS = [("hp", "Width (HP)"), ("depth_mm", "Depth (mm)"), ("ma_p12", "+12V (mA)"), ("ma_m12", "-12V (mA)"), ("ma_p5", "+5V (mA)")]
RAILS = FIELDS[2:]
RANK = {"conflict": 5, "missing": 4, "inferred": 3, "override": 2, "single": 1, "confirmed": 0}


def resolve(field, sources, override):
    if field in override:
        o = override[field]
        return {"value": o["value"], "status": o.get("status", "override"), "basis": o.get("basis", ""), "seen": []}
    seen = [(s["tier"], s["url"], s["values"][field], s["values"].get(field + "_line", "")) for s in sources if field in s["values"]]
    if not seen:
        return {"value": None, "status": "missing", "basis": "", "seen": []}
    counts = Counter(v[2] for v in seen)
    if len(counts) == 1:
        return {"value": seen[0][2], "status": "confirmed" if len(seen) >= 2 else "single", "basis": "", "seen": seen}
    top, n = counts.most_common(1)[0]
    value = top if n > len(seen) / 2 else max(counts)            # conservative for power: the larger figure
    return {"value": value, "status": "conflict", "basis": "Sources disagree: " + ", ".join(f"{t}={v}" for t, _, v, _ in seen), "seen": seen}


def build(items, docs):
    overrides = yaml.safe_load((ROOT / "eurorack" / "overrides.yaml").read_text()) or {}
    cfg = yaml.safe_load((ROOT / "eurorack" / "sources.yaml").read_text())["modules"]
    mods = {}
    for it in items:
        ev = ROOT / "eurorack" / "evidence" / f"{it['id']}.json"
        if not it["category"].startswith("eurorack") or not ev.exists():
            continue
        rec, ov = json.loads(ev.read_text()), overrides.get(it["id"], {})
        res = {f: resolve(f, rec["sources"], ov) for f, _ in FIELDS}
        mods[it["id"]] = {"item": it, "rec": rec, "ov": ov, "res": res,
                          # "weakest" ignores fields the budget does not need when absent: many modules simply do not state a
                          # +5V figure or a depth. Their absence is shown on the module page, not here.
                          "worst": max((r["status"] for f, r in res.items() if not (r["status"] == "missing" and f in ("ma_p5", "depth_mm"))),
                                       key=lambda s: RANK[s]),
                          "confirmed": sum(1 for r in res.values() if r["status"] == "confirmed")}

    out = docs / "eurorack"
    out.mkdir(parents=True, exist_ok=True)
    for old in out.glob("*.md"):
        old.unlink()

    def fmt(r):
        return "-" if r["value"] is None else str(r["value"])

    # ---- module cards ----
    for mid, m in mods.items():
        it, res, ov, rec = m["item"], m["res"], m["ov"], m["rec"]
        supply = ov.get("role") == "supply"
        fm = {"title": it["name"], "doc_type": "eurorack-module", "module": mid, "manufacturer": it.get("manufacturer"),
              "category": it["category"], "format": it.get("format", "3U"), "in_use": it.get("in_use", True),
              "function": ov.get("function"), "role": ov.get("role", "module"),
              "specs": {"hp": res["hp"]["value"], "depth_mm": res["depth_mm"]["value"],
                        ("capacity_ma" if supply else "power_ma"): {"+12V": res["ma_p12"]["value"], "-12V": res["ma_m12"]["value"], "+5V": res["ma_p5"]["value"]}},
              "spec_status": {f: r["status"] for f, r in res.items()}, "identified_as": rec.get("match_note"),
              "content_status": "generated"}
        fm = {k: v for k, v in fm.items() if v is not None}
        b = [f"# {it['name']}", ""]
        if ov.get("function"):
            b += [f"**Function:** {ov['function']}. *(Description from ModularGrid/retailer text; not verified against a manual.)*", ""]
        if rec.get("match_note"):
            b += [f"> **Identification:** {rec['match_note']}", ""]
        if it.get("note"):
            b += [f"> {it['note']}", ""]
        if ov.get("notes"):
            b += [f"> {ov['notes']}", ""]
        b += ["## Specifications", "", "| Field | Value | Status | Basis |", "|---|---|---|---|"]
        for f, label in FIELDS:
            r = res[f]
            name = label.replace("(mA)", "(mA supplied)") if supply and f.startswith("ma_") else label
            if it["category"] == "eurorack-case" and f == "hp":
                name = "Usable case area (HP)"
            src = "; ".join(f"{t}: {v}" for t, _, v, _ in r["seen"]) or "no source stated it"
            b.append(f"| {name} | {fmt(r)} | {r['status']} | {r['basis'] or src} |")
        b += ["", "*confirmed = two or more sources agree; single = one source only; inferred/override = a decision with the reasoning shown; missing = not stated in any source that could be read.*", "",
              "## Evidence: the exact lines each number came from", "", "| Field | Source | Value | Line | Page |", "|---|---|---|---|---|"]
        for f, label in FIELDS:
            for tier, url, val, line in res[f]["seen"]:
                b.append(f"| {label} | {tier} | {val} | `{line.replace('|', '/')}` | <{url}> |")
        b += ["", f"Fetched {rec['fetched']}. Pages: " + ", ".join(f"<{s['url']}> (HTTP {s['http']})" for s in rec["sources"])]
        (out / f"{mid}.md").write_text(f"---\n{yaml.safe_dump(fm, sort_keys=False, allow_unicode=True, width=1000)}---\n\n{GEN}\n\n" + "\n".join(b) + "\n", encoding="utf-8")

    # ---- overview ----
    supply_ids = [k for k, m in mods.items() if m["ov"].get("role") == "supply"]
    consumers = [m for k, m in mods.items() if k not in supply_ids and m["item"].get("in_use", True) is not False]
    rows = ["| Module | Format | HP | +12V | -12V | +5V | Weakest field status |", "|---|---|---|---|---|---|---|"]
    for k, m in sorted(mods.items(), key=lambda kv: kv[1]["item"]["name"].lower()):
        r = m["res"]
        rows.append(f"| [{m['item']['name']}]({k}.md) | {m['item'].get('format', '3U')} | {fmt(r['hp'])} | {fmt(r['ma_p12'])} | {fmt(r['ma_m12'])} | {fmt(r['ma_p5'])} | {m['worst']} |")
    pending = [i for i in items if i["category"].startswith("eurorack") and i["id"] not in mods and i.get("in_use", True) is not False]
    unused = [i for i in items if i["category"].startswith("eurorack") and i.get("in_use", True) is False]
    tally = Counter(r["status"] for m in mods.values() for r in m["res"].values())
    b = ["# Eurorack", "", f"{len(mods)} modules have spec pages. Every number keeps the source it came from; see each module's *Evidence* table.", "",
         "Field status across all modules: " + ", ".join(f"{n} {s}" for s, n in sorted(tally.items(), key=lambda x: -x[1])) + ".", "",
         "See the [power budget](power-budget.md).", ""] + rows
    if pending:
        b += ["", "## Not yet covered", "", "In use, but not identified confidently enough to look up (see the inventory's open questions):", ""] + [f"- {i['name']}" for i in pending]
    if unused:
        b += ["", "## Marked unused", ""] + [f"- {i['name']}" for i in unused]
    (out / "index.md").write_text(f"---\ntitle: Eurorack\ndoc_type: eurorack-index\ncontent_status: generated\n---\n\n{GEN}\n\n" + "\n".join(b) + "\n", encoding="utf-8")

    # ---- power budget ----
    supplies = [mods[k] for k in supply_ids]
    def cap_of(m, f):
        return m["res"][f]["value"]
    def kind(m):
        return "peak" if m["item"]["category"] == "eurorack-case" else "rated"
    b = ["# Power budget", "",
         "Supplies recorded: " + "; ".join(f"**{m['item']['name']}** ({kind(m)}: " + ", ".join(f"{lab.split()[0]} {cap_of(m, f)} mA" for f, lab in RAILS) + ")" for m in supplies) + ".", "",
         f"Assumption: every module marked in use is installed and running at once ({len(consumers)} modules with specs). "
         "Which module sits in which case, and which supply feeds it, is not recorded. So each supply is compared with the "
         "**whole** load, and a combined column shows the best case where the load can be split perfectly. "
         "This is a paper budget from published figures, not a measurement.", "",
         "| Rail | Total draw (mA) | " + " | ".join(f"{m['item']['name']} alone" for m in supplies) + " | All supplies combined | Modules with no figure |",
         "|---|---|" + "---|" * len(supplies) + "---|---|"]
    verdict = {}
    for f, lab in RAILS:
        vals = [(m["item"]["name"], m["res"][f]["value"]) for m in consumers]
        total = sum(v for _, v in vals if v is not None)
        unknown = [n for n, v in vals if v is None]
        lower = " (lower bound)" if unknown else ""
        cells, caps = [], []
        for m in supplies:
            c = cap_of(m, f)
            caps.append(c or 0)
            cells.append("-" if not c else f"{c} ({100 * total / c:.0f}%)")
        comb = sum(caps)
        verdict[f] = (total, comb)
        b.append(f"| {lab.split()[0]} | {total}{lower} | " + " | ".join(cells) + f" | {comb} ({100 * total / comb:.0f}%) | {len(unknown)} |" if comb else f"| {lab.split()[0]} | {total}{lower} | - | - | {len(unknown)} |")
    b += ["", "Percentages are draw as a share of capacity. A rail marked *lower bound* omits modules whose figure no source stated. "
          "Case figures are labelled *peak* by the maker; continuous capacity may be lower.", ""]
    hp3 = sum(m["res"]["hp"]["value"] or 0 for m in consumers if m["item"].get("format", "3U") != "1U")
    hp1 = sum(m["res"]["hp"]["value"] or 0 for m in consumers if m["item"].get("format") == "1U")
    case_hp = [(m["item"]["name"], m["res"]["hp"]["value"]) for m in supplies if m["item"]["category"] == "eurorack-case"]
    conns = [(m["item"]["name"], m["ov"].get("connections")) for m in supplies if m["ov"].get("connections")]
    b += [f"**Width:** {hp3} HP of standard 3U modules, plus {hp1} HP-equivalent of 1U-format (Intellijel) modules as listed by ModularGrid, which sit in a separate 1U row." +
          (" Case space recorded: " + ", ".join(f"{n} {h} HP" for n, h in case_hp) + ". The modules total more than that, so some live in a case or rack that is not recorded here." if case_hp and hp3 > sum(h or 0 for _, h in case_hp) else ""), "",
          f"**Connections:** {len(consumers)} modules counted; recorded power connections: " + (", ".join(f"{n} {c}" for n, c in conns) or "none") + ". Extra distribution boards, if any, are not recorded.", "",
          "## Per module", "", "| Module | HP | +12V | -12V | +5V | Weakest status |", "|---|---|---|---|---|---|"]
    for m in sorted(consumers, key=lambda m: -(m["res"]["ma_p12"]["value"] or 0)):
        r = m["res"]
        b.append(f"| [{m['item']['name']}]({m['item']['id']}.md) | {fmt(r['hp'])} | {fmt(r['ma_p12'])} | {fmt(r['ma_m12'])} | {fmt(r['ma_p5'])} | {m['worst']} |")
    if pending:
        b += ["", "## Not in this budget", ""] + [f"- {i['name']}: not identified yet" for i in pending]
    b += ["", "## How much to trust it", "",
          "Status per field is on each module page. Figures marked *single* rest on one source (usually ModularGrid, which is user-maintained). "
          "Figures marked *inferred* are zero-draw assumptions for passive or jacks-only modules."]
    (out / "power-budget.md").write_text(f"---\ntitle: Power budget\ndoc_type: eurorack-budget\ncontent_status: generated\n---\n\n{GEN}\n\n" + "\n".join(b) + "\n", encoding="utf-8")

    nav = [{"Overview": "eurorack/index.md"}, {"Power budget": "eurorack/power-budget.md"}] + \
          [{m["item"]["name"]: f"eurorack/{k}.md"} for k, m in sorted(mods.items(), key=lambda kv: kv[1]["item"]["name"].lower())]
    llms = ["## Eurorack", "", "- [Eurorack overview](eurorack/): module specs with sources", "- [Power budget](eurorack/power-budget/): rail totals vs supply capacity"] + \
           [f"- [{m['item']['name']}](eurorack/{k}/)" + (f": {m['ov']['function']}" if m["ov"].get("function") else "") for k, m in sorted(mods.items(), key=lambda kv: kv[1]["item"]["name"].lower())] + [""]
    cards = {k: f"specs {m['confirmed']}/5 confirmed, weakest: {m['worst']}" for k, m in mods.items()}
    budget = {}
    for f, lab in RAILS:
        vals = [m["res"][f]["value"] for m in consumers]
        budget[lab.split()[0]] = {"draw_ma": sum(v for v in vals if v is not None), "capacity_ma": sum(cap_of(m, f) or 0 for m in supplies),
                                  "modules_without_figure": sum(1 for v in vals if v is None),
                                  "per_supply": {m["item"]["name"]: cap_of(m, f) for m in supplies}}
    matrix = [{"id": k, "name": m["item"]["name"], "format": m["item"].get("format", "3U"),
               "statuses": {f: m["res"][f]["status"] for f, _ in FIELDS}, "values": {f: m["res"][f]["value"] for f, _ in FIELDS}}
              for k, m in sorted(mods.items(), key=lambda kv: kv[1]["item"]["name"].lower())]
    return {"matrix": matrix, "fields": FIELDS, "nav": nav, "llms": llms, "cards": cards, "count": len(mods), "consumers": len(consumers),
            "tally": dict(tally), "budget": budget, "supplies": [m["item"]["name"] for m in supplies]}
